[pytest]
addopts = -s -v
 --alluredir allure-results --junitxml reports/junit-report.xml --asyncio-mode=auto

markers =
        api: pytest mark used for API tests
        websocket: pytest mark used for WebSocket tests
        api_token
        smoke: pytest mark used for Smoke tests
        ui: pytest mark used for UI tests

junit_family=legacy

asyncio_default_fixture_loop_scope = function