name: Automated tests

on:
    workflow_dispatch:
      inputs:
        deployment_target:
          description: Choose targer
          required: true
          default: all_tests
          type: choice
          options:
            - all_tests
            - websocket_tests
            - api_async_tests

jobs:
    test:
        runs-on: ubuntu-latest
    
        steps:
          - name: Checkout repository
            uses: actions/checkout@v3
          - name: setup Python
            uses: actions/setup-python@v4
            with:
                python-version: "3.11"
          - name: Install poetry
            run: pip install poetry
          - name: Install dependencies
            run: poetry install --no-root
          - name: all_tests
            if: 'github.event.inputs.deployment_target == "all_tests"'
            run: poetry run pytest
          - name: websocket_tests
            if: 'github.event.inputs.deployment_target == "websocket_tests"'
            run: poetry run pytest -m "websocket"
          - name: api_async_tests
            if: 'github.event.inputs.deployment_target == "api_async_tests"'
            run: poetry run pytest -m "api_async"
